spring:
  application:
    name: front-service-hystrix-client
server:
  port: 8186
  servlet:
    context-path: /market

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
