server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#spring:
#  cloud:
#    config:
#      uri: http://localhost:8081
#
## spring.cloud.config.username=root
## spring.cloud.config.password=s3cr3t
## spring.cloud.config.name=conf
## spring.cloud.config.uri=http://localhost:8081